spring.application.name=articles
# Derby client DB in project root
spring.datasource.driver-class-name=org.apache.derby.jdbc.ClientDriver
spring.datasource.url=jdbc:derby://localhost:1527/articlesDB;create=true
spring.datasource.username=
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.community.dialect.DerbyDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_nationalized_character_data=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.web.error.include-message=always

spring.web.resources.static-locations=classpath:/static/
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.html

server.port=8080




